export enum EPrivilege {
    USER_MANAGER = "USER_MANAGER",
    ROLE_MANAGER = "ROLE_MANAGER",
    SERVICE_MANAGER = "SERVICE_MANAGER",
    CALENDAR_DATE_MANAGER = "CALENDAR_DATE_MANAGER",
    STOP_MANAGER = "STOP_MANAGER",
    ROUTE_MANAGER = "ROUTE_MANAGER",
    CONDUCTOR = "CONDUCTOR",
    REPORTS_VIEWER = "REPORTS_VIEWER",
    TRIP_MONITOR = "TRIP_MONITOR",
}