export enum ERole {
    ADMIN = "ROLE_ADMIN",
    BUSROUTEMANAGER = "ROLE_BUSROUTEMANAGER",
    BUSMANAGER = "ROLE_BUSMANAGER",
    BUSSTOPMANAGER = "ROLE_BUSSTOPMANAGER",
    CONDUCTORMANAGER = "ROLE_CONDUCTORMANAGER",
    CONDUCTOR = "ROLE_CONDUCTOR",
    USER = "ROLE_USER",
}